# version: "3.9"
services:
  goapp:
    build: .
    ports:
      - '8080:8080'
    environment:
      - ENABLE_DB=true
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_PASSWORD=secret
      - DB_DATABASE=app_db
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
