pipeline {
    // install golang 1.14 on Jenkins node
    agent any
    tools {
        go 'go1.19.4'
    }

    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0 
        GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
    }

    stages {
        stage("build") {
            steps {
                echo 'BUILD PROCESS STARTED'
                bat 'make build'
            }
        }
        stage("test") {
            steps {
                echo 'UNIT TEST INITIATED'
                bat 'make test'
            }
    }
}